name: baseDmux
channels:
    - bioconda
    - conda-forge
    - defaults
    - anaconda
dependencies:
    - snakemake = 6.0.0
    - pygraphviz = 1.7
    - python = 3.8
    - ruamel.yaml = 0.16.12
    - pandas = 1.1.4
