name: baseDmux
channels:
    - bioconda
    - conda-forge
    - defaults
    - anaconda
dependencies:
    - snakemake = 7.14.0
    - pygraphviz = 1.7
    - python = 3.8
    - ruamel.yaml = 0.17.21
    - pandas = 1.5.0
