#!/usr/bin/env Rscript

## subset sequencing_summary.txt file according to barcoding_summary.txt or classification file
## then put them to corresponding barcode folders

args <- commandArgs(trailingOnly = TRUE)

sequencingFile = args[1] # path to sequencing_summary.txt file
barcodingPath = args[2] # folder containing barcoding_summary.txt or classification and barcode folder

# barcodingPath = "/home/baotram/tal/workflow/demultiplex/deepbinner/20190411_1245_MN25256_FAH93041_8a9c834e"
# sequencingFile = "/home/baotram/tal/workflow/basecall/20190411_1245_MN25256_FAH93041_8a9c834e/sequencing_summary.txt"
# barcodingFile = "/home/baotram/tal/workflow/demultiplex/deepbinner/20190411_1245_MN25256_FAH93041_8a9c834e/classification"

sequencing <- read.table(sequencingFile, header = TRUE)

summaries = list.files(barcodingPath, pattern = "barcoding_summary.txt", full.names = TRUE)
if (length(summaries) > 0) { # This is barcoding_summary.txt generated by guppy_barcoder
  for (s in summaries) {
    barcoding <- read.table(s, header = TRUE)
    outPath = dirname(s)
    barcodelist <- levels(barcoding$barcode_arrangement)

    for (barcode in barcodelist) {
      summary <- file.path(outPath, barcode, "sequencing_summary.txt")
      reads <- barcoding[barcoding$barcode_arrangement == barcode, "read_id"]
      readsOfBarcode <- sequencing[sequencing$read_id %in% reads,]
      write.table(readsOfBarcode, summary, sep = "\t", row.names = FALSE, quote = FALSE)
    }
    print(paste(length(barcodelist), "sequencing_summary.txt files created"))
  }

} else {# This is classification generated by deepbinner classify
  summaries = list.files(barcodingPath, pattern = "classification", full.names = TRUE)
  if (length(summaries) > 0) {
    for (s in summaries) {
      barcoding <- read.table(s, header = TRUE)
      outPath = dirname(s)
      barcodelist <- levels(barcoding$barcode_call)

      for (barcode in barcodelist) {
        foldername <- ifelse(!is.numeric(type.convert(barcode, numerals = "no.loss")), ifelse(barcode == "none", "unclassified", barcode), sprintf("barcode%02d", type.convert(barcode)))
        summary_path  <- file.path(outPath, foldername)
        mkdir_cmd = paste("mkdir -p", summary_path)
        system(mkdir_cmd)
        summary <- file.path(summary_path, "sequencing_summary.txt")
        reads <- barcoding[barcoding$barcode_call == barcode, "read_ID"]
        readsOfBarcode <- sequencing[sequencing$read_id %in% reads,]
        write.table(readsOfBarcode, summary, sep = "\t", row.names = FALSE, quote = FALSE)
      }
      print(paste(length(barcodelist), "sequencing_summary.txt files created"))
    }

  } else {print("No barcoding_summary.txt or classification files exist.")}
}
